/*
This file contains code for sending the
client's public key to the default server and
receiving the assigned IP.
 */

package com.example.wifisecure.vpn

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject

object HttpApi {
    // IP address of the default vpn server
    private const val BASE_URL = "http://157.230.133.120:8000"

    // Used to perform HTTP requests.
    private val client = OkHttpClient()
    // Media type for sending JSON to the server.
    private val JSON_MEDIA_TYPE = "application/json; charset=utf-8".toMediaType()

    /*
    The code below was generated by ChatGPT5. The code was commented by me.
     */
    // Sends the client's public key to the server and receives the assigned IP.
    suspend fun registerPeer(publicKey: String): String = withContext(Dispatchers.IO) {
        // Builds the JSON object.
        val json = JSONObject().apply {
            put("public_key", publicKey)
        }.toString()

        // Convert the JSON string into a Http request body.
        val body = json.toRequestBody(JSON_MEDIA_TYPE)

        // Builds the HTTP POST request
        val request = Request.Builder()
            .url("$BASE_URL/register-peer")
            .post(body)
            .addHeader("Content-Type", "application/json")
            .build()

        // Executes the HTTP request.
        client.newCall(request).execute().use { response ->
            if (!response.isSuccessful) {
                throw IllegalStateException("register-peer failed: HTTP ${response.code}")
            }

            val responseBody = response.body?.string()
                ?: throw IllegalStateException("Empty response body")

            val jsonResp = JSONObject(responseBody)
            val IP = jsonResp.getString("ip")

            // Returns the IP.
            IP
        }
    }
}
